<?php
$ip[0] = "192.168.1.2";
$ip[1] = "192.168.1.187";
$ip[2] = "192.168.1.188";
$ip[3] = "192.168.1.189";
$ip[4] = "192.168.1.190";
$ip[5] = "192.168.1.191";
$ip[6] = "192.168.1.192";
$ip[7] = "192.168.1.186";
$stmadres[0] = 0;//contante *do not change*
$stmadres[1] = 1;//contante *do not change*
$stmadres[2] = 2;//contante *do not change*
$stmadres[3] = 3;//contante *do not change* 
$stmadres[4] = 132;//contante *do not change* 
$stmadres[5] = 133;//contante *do not change*
$stmadres[6] = 134;//contante *do not change*
$stmadres[7] = 135;//contante *do not change* 
$xmlpoort = 6680;//contante
$communicator_type =  0;
$refreshtimeout = 3000;
$language = "nl";
$icon_size = 48;
$button_label_width = 250;
$button_width = 450;
$dimmer_steps = 4;
$aknowledge = "";//antwoord na een commando
$respons = "";//antwoord na uidrukkelijk feedback te vragen , dus xml data opvragen

?>
